apiVersion: v1
kind: Pod
metadata:
  name: iris-pod
  labels:
    app: iris

spec:
  containers:
    - name: iris-container
      image: fjsoto/iris_model:v2
      ports:
        - containerPort: 5002
