apiVersion: v1
kind: Service
metadata:
  name: iris-service
spec:
  type: NodePort
  selector:
    app: iris
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
      nodePort: 30002
